<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Tipo de habitacion";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Room");

foreach ($this->languages as $language) {
    $active = false;
    if ($this->Language == $language->LanId) {
        $active = true;
    }
    
    $form->addTab($language->LanName, Com_Helper_Url::getInstance()->urlBase . "/Admin/Room/Edit/lan/" . $language->LanId . "/id/" . $this->Id, $active);  
    $form->addTab("Imagenes (" . $language->LanName . ")", Com_Helper_Url::getInstance()->urlBase . "/Admin/Room/Images/lan/" . $language->LanId . "/id/" . get('id'), false);
}

$control = new Com_Wizard_Form_Control_Hidden();
$control->name = "Language";
$control->default = $this->Language;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Name";
$control->label = "Tipo de Habitacion";
$control->default = $this->Name;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control_Editor();
$control->name = "Resume";
$control->label = "Resumen";
$control->default = $this->Resume;
$form->add($control);

$control = new Com_Wizard_Form_Control_Editor();
$control->name = "Description";
$control->label = "Description";
$control->default = $this->Description;
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Amenities";
$control->label = "Amenities";
$control->default = $this->Amenities;
$control->rows = 3;
$control->addParameter("style ", "height:120px;");
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Services";
$control->label = "Servicios";
$control->default = $this->Services;
$control->rows = 3;
$control->addParameter("style ", "height:120px;");
$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Image";
$control->label = "Imagen";
$control->default = $this->Image;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Habilitado');
$control->addItem('0', 'Bloqueado');

$form->add($control);

$form->render();
