<?PHP

$db = new Entities_RoomType();
$grid = new Com_Wizard_Grid();
$grid->title = "Tipos de Habitaciones";
$grid->setIdField("TypeId");
$grid->setLanField("TypeLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "TypeName" => "Tipo", "TypeStatus" => "Estado"));
$grid->setFilters(array("TypeName" => get('TypeName')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Room/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Room/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Room/Delete/id/_ID_' . "':'';");

$grid->customField("TypeStatus", array("value" => array('1' => 'Habilitado', '0' => 'Bloqueado')));

$grid->render();
