<?PHP

$db = new Entities_History();
$grid = new Com_Wizard_Grid();
$grid->title = "Historia";
$grid->setIdField("HisId");
$grid->setLanField("HisLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "HisTitle" => "Titulo", "HisStatus" => "Estado"));
$grid->setFilters(array("HisTitle" => get('HisTitle')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/History/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);


$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/History/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/History/Delete/id/_ID_' . "':'';");

$grid->render();
