<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Salones de eventos";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Hall");

foreach ($this->languages as $language) {
    $active = false;
    if ($this->Language == $language->LanId) {
        $active = true;
    }
    
    $form->addTab($language->LanName, Com_Helper_Url::getInstance()->urlBase . "/Admin/Hall/Edit/lan/" . $language->LanId . "/id/" . $this->Id, $active);  
    $form->addTab("Imagenes (" . $language->LanName . ")", Com_Helper_Url::getInstance()->urlBase . "/Admin/Hall/Images/lan/" . $language->LanId . "/id/" . get('id'), false);
}

$control = new Com_Wizard_Form_Control_Hidden();
$control->name = "Language";
$control->default = $this->Language;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Name";
$control->label = "Nombre";
$control->default = $this->Name;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control_Editor();
$control->name = "Resume";
$control->label = "Resumen";
$control->default = $this->Resume;
$form->add($control);

$control = new Com_Wizard_Form_Control_Editor();
$control->name = "Description";
$control->label = "Description";
$control->default = $this->Description;
$form->add($control);

$control = new Com_Wizard_Form_Control_Editor();
$control->name = "Amenities";
$control->label = "Amenities";
$control->default = $this->Amenities;
$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Image";
$control->label = "Imagen";
$control->default = $this->Image;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_File();
$control->name = "Capacity";
$control->label = "Capacidad";
$control->default = $this->Capacity;
$control->isImage = true;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Habilitado');
$control->addItem('0', 'Bloqueado');
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Type";
$control->label = "Tipo";
$control->default = $this->Type;
$control->required = true;
$control->addItem('1', 'Banner');
$control->addItem('0', 'Normal');
$form->add($control);

$form->render();
