<article>
    <section class="section">
        <div class="background-media" data-0-top-bottom="background-position: 50% -120px"
             data-start="background-position: 50% 0px"
             style="background-image: url(<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?php echo $this->hall->HallImage; ?>); background-repeat:no-repeat; background-size:cover; background-attachment:fixed; background-position: 50% 0%;">
        </div>
        <div class="background-overlay grid-overlay-0" style="background-color: rgba(0,0,0,0.2);"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="divider-wrapper">
                        <div class="visible-xs element-height-50"></div>
                        <div class="visible-sm element-height-100"></div>
                        <div class="visible-md element-height-200"></div>
                        <div class="visible-lg element-height-200"></div>
                    </div>
                    <h1 class="text-center element-bottom-20 text-light os-animation super" data-os-animation="fadeIn"
                        data-os-animation-delay="0.1s">
                        <?php echo $this->hall->HallName; ?>
                    </h1>
                    <div class="figure element-bottom-100 os-animation" data-os-animation="fadeIn"
                         data-os-animation-delay="0.3s"> <span class="figure-image">
                     <!-- <img alt="decor-big-white.png" src="<?PHP //echo Com_Helper_Url::getInstance()->getImage();  ?>/Public/hotel/decor-big-white.png"> -->
                        </span></div>
                </div>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="background-overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <h2 class="text-center element-top-60 os-animation" data-os-animation="fadeIn"
                        data-os-animation-delay="0.1s">
                        <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'titleComodidades')->TxtDescription; ?>
                    </h2>
                    <div class="figure element-bottom-20 block text-center os-animation" data-os-animation="fadeIn"
                         data-os-animation-delay="0.2s"> <span class="figure-image">
                            <img alt="decor-small-gold.png"
                                 src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/decor-small-gold.png">
                        </span></div>
                    <div class="col-text-1 os-animation" data-os-animation="fadeIn" data-os-animation-delay="0.3s">
                        <p><?php echo $this->hall->HallDescription; ?></p>
                    </div>
                    <ul class="skills-list element-top-20 element-bottom-20 os-animation" data-os-animation="fadeIn"
                        data-os-animation-delay="0.4s">
                        <?php
                        $arreglo = explode(',', $this->hall->HallAmenities);
                        for ($j = 0; $j < count($arreglo); $j++)
                            echo '<li>' . $arreglo[$j] . '</li>';
                        ?>

                    </ul>
                    <div class="capacidad">

                        <div
                            class="figure portfolio-os-animation image-filter-onhover fade-in text-left figcaption-middle normalwidth"
                            data-os-animation="fadeIn" data-os-animation-delay="0.1s">
                            <a class="figure-image"
                               href="#"
                               target="_self">
                                <img class="type-hall normalwidth"
                                     src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/banquete.png">
                                <div class="figure-overlay">
                                    <div class="figure-overlay-container">
                                        <div class="figure-caption"> Cap:
                                            <br> <?php echo $this->hall->HallBaquete; ?> </i> </div>
                                    </div>
                                </div>
                            </a>
                            <h5 style="text-align: center; margin: 0; color:#51575b;"> <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtBanquete')->TxtDescription; ?></h5>
                        </div>

                        <div
                            class="figure portfolio-os-animation image-filter-onhover fade-in text-left figcaption-middle normalwidth"
                            data-os-animation="fadeIn" data-os-animation-delay="0.1s">
                            <a class="figure-image"
                               href="#"
                               target="_self">
                                <img class="type-hall normalwidth"
                                     src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/aula.png">
                                <div class="figure-overlay">
                                    <div class="figure-overlay-container">
                                        <div class="figure-caption"> Cap: <br> <?php echo $this->hall->HallAula; ?> </i>
                                        </div>
                                    </div>
                                </div>
                            </a>
                            <h5 style="text-align: center; margin: 0; color:#51575b;"><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtAula')->TxtDescription; ?></h5>
                        </div>

                        <div
                            class="figure portfolio-os-animation image-filter-onhover fade-in text-left figcaption-middle normalwidth"
                            data-os-animation="fadeIn" data-os-animation-delay="0.1s">
                            <a class="figure-image"
                               href="#"
                               target="_self">
                                <img class="type-hall normalwidth"
                                     src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/cocktail.png">
                                <div class="figure-overlay">
                                    <div class="figure-overlay-container">
                                        <div class="figure-caption"> Cap:
                                            <br> <?php echo $this->hall->HallCocktail; ?> </i> </div>
                                    </div>
                                </div>
                            </a>
                            <h5 style="text-align: center; margin: 0; color:#51575b;"><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtCocktail')->TxtDescription; ?></h5>
                        </div>

                        <div
                            class="figure portfolio-os-animation image-filter-onhover fade-in text-left figcaption-middle normalwidth"
                            data-os-animation="fadeIn" data-os-animation-delay="0.1s">
                            <a class="figure-image"
                               href="#"
                               target="_self">
                                <img class="type-hall normalwidth"
                                     src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/teatro.png">
                                <div class="figure-overlay">
                                    <div class="figure-overlay-container">
                                        <div class="figure-caption"> Cap:
                                            <br> <?php echo $this->hall->HallTeatro; ?> </i> </div>
                                    </div>
                                </div>
                            </a>
                            <h5 style="text-align: center; margin: 0; color:#51575b;"><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtTeatro')->TxtDescription; ?></h5>
                        </div>

                        <div
                            class="figure portfolio-os-animation image-filter-onhover fade-in text-left figcaption-middle normalwidth"
                            data-os-animation="fadeIn" data-os-animation-delay="0.1s">
                            <a class="figure-image"
                               href="#"
                               target="_self">
                                <img class="type-hall normalwidth"
                                     src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/u.png">
                                <div class="figure-overlay">
                                    <div class="figure-overlay-container">
                                        <div class="figure-caption"> Cap: <br> <?php echo $this->hall->HallU; ?> </i>
                                        </div>
                                    </div>
                                </div>
                            </a>
                            <h5 style="text-align: center; margin: 0; color:#51575b;"><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtU')->TxtDescription; ?></h5>
                        </div>


                    </div>
                </div>

                <div class="col-md-9">
                    <?php Hall_Widget_Gallery::getInstance()->setLan($this->lan)->setHall($this->hall->HallId)->render(); ?>
                </div>
            </div>
        </div>
    </section>
    <section class="section hidden">
        <div class="background-media"
             style="background-image: url(<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?php echo $this->hall->HallImage; ?>); background-repeat:no-repeat; background-size:cover; background-attachment:fixed; background-position: 50% 0%;"></div>
        <div class="background-overlay grid-overlay-0" style="background-color: rgba(0,0,0,0.7);"></div>
        <div class="container container-vertical-middle">
            <div class="row vertical-middle">
                <div class="col-md-12 text-center">
                    <div class="capacidad">
                        <img src="<?php echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/aula.png">
                        <img src="<?php echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/banquete.png">
                        <img src="<?php echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/cocktail.png">
                        <img src="<?php echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/teatro.png">
                        <img src="<?php echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/u.png">
                    </div>


                    <div class="divider-wrapper">
                        <div class="visible-xs element-height-40"></div>
                        <div class="visible-sm element-height-40"></div>
                        <div class="visible-md element-height-40"></div>
                        <div class="visible-lg element-height-40"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</article>