<?PHP

$db = new Entities_Review();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado de Opiniones";
$grid->setIdField("RevId");
$grid->setQuery($db->getList());
$grid->setAlias(array("RevComment" => "Comentario", "RevSource" => "Origen", "RevStatus" => "Estado"));
$grid->setFilters(array("RevName" => get('RevName')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Reviews/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Reviews/Edit/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Reviews/Delete/id/_ID_' . "':'';");

$grid->customField("RevStatus", array("value" => array('1' => 'Leido', '0' => 'No Leido')));

$grid->render();
