<?PHP

$db = new Entities_Promo();
$grid = new Com_Wizard_Grid();

$grid->title = "Listado de Promociones";
$grid->setIdField("ProId");
$grid->setLanField("ProLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "ProDate" => "Fecha", "ProTitle" => "Titulo", "ProStatus" => "Estado"));
$grid->setFilters(array("ProTitle" => get('ProTitle')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Promos/Add/');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Promos/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Promos/Delete/id/_ID_' . "':'';");

$grid->customField("ProStatus", array("value" => array('1' => 'Habilitado', '0' => 'Bloqueado')));
$grid->customField("ProDate", array("dateFormat" => "d/m/Y"));

$grid->render();
