<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Seo";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/Seo");

foreach ($this->languages as $language) {
    $active = false;
    if ($this->Language == $language->LanId) {
        $active = true;
    }
    $form->addTab($language->LanName, Com_Helper_Url::getInstance()->urlBase . "/Admin/Seo/Edit/lan/" . $language->LanId . "/id/" . $this->Id, $active);
}

$control = new Com_Wizard_Form_Control_Hidden();
$control->name = "Language";
$control->default = $this->Language;
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Title";
$control->label = "Titulo";
$control->default = $this->Title;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "ShortDescription";
$control->label = "Descripcion Corta";
$control->default = $this->ShortDescription;
$control->required = true;
$control->rows = 2;
$control->addParameter("style ", "height:90px;
            ");
$form->add($control);

$control = new Com_Wizard_Form_Control_Text();
$control->name = "Description";
$control->label = "Descripcion";
$control->default = $this->Description;
$control->required = true;
$control->rows = 3;
$control->addParameter("style ", "height:120px;
            ");
$form->add($control);

$control = new Com_Wizard_Form_Control();
$control->name = "Page";
$control->label = "Pagina";
$control->default = $this->Page;
$control->required = true;
$control->length = 50;
$form->add($control);

$form->render();
