<?PHP

$db = new Entities_Seo();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado Seo Paginas";
$grid->setIdField("SeoId");
$grid->setLanField("SeoLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "SeoTitle" => "Title", "SeoPage" => "Pagina"));
$grid->setFilters(array("SeoPage" => get('SeoPAge')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Seo/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Seo/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Seo/Delete/id/_ID_' . "':'';");

$grid->render();
