<!doctype html>
<html class="no-js" lang="">

    <head>
        <meta charset="utf-8">

        <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">
        <title><?php echo Configurations_Helper_Configuration::getInstance()->getKey("PAGE_TITLE"); ?></title>
        <meta name="description" content="<?php echo Configurations_Helper_Configuration::getInstance()->getKey("PAGE_DESCRIPTION"); ?>">
        <meta name=”robots” content=”Index,Follow”>
        <meta name=”google” content=”nositelinkssearchbox”>
        <meta name="Author" content="Qwerty Bolivia">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel='stylesheet' id='open-sans-css'
              href='//fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=4.1'
              type='text/css' media='all'/>
        <link
            href="//fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,700,800%7CPlayfair+Display:400,400italic,700,900&amp;subset=greek,latin,latin"
            rel="stylesheet" type="text/css">


        <!-- Fav and Touch Icons -->
        <meta name="msapplication-TileColor" content="#d9534f">
        <meta name="msapplication-TileImage"
              content="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/ms-icon-144x144.png">
        <meta name="msapplication-config"
              content="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public//favicons/browserconfig.xml">
        <meta name="theme-color" content="#ffffff">
        <link rel="apple-touch-icon" sizes="57x57"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-180x180.png">
        <link rel="icon" type="image/png"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-32x32.png"
              sizes="32x32">
        <link rel="icon" type="image/png"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/android-192x192.png"
              sizes="192x192">
        <link rel="icon" type="image/png"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-96x96.png"
              sizes="96x96">
        <link rel="icon" type="image/png"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-16x16.png"
              sizes="16x16">
        <link rel="manifest" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/manifest.json">
        <link rel="shortcut icon"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon.ico"
              type="image/x-icon"/>

        <?PHP
        Com_Helper_Style::getInstance()
                ->addFile("Public/extras.min.css")
                ->addFile("Public/bootstrap.css")
                ->addFile("Public/font-awesome.min.css")
                ->addFile("Public/fonts.css")
                ->addFile("Public/theme.css")
                ->addFile("Public/hotel.css");
        echo Com_Helper_Style::getInstance();
        ?>
    </head>

    <body class="transparent-header pace-on pace-dot">
        <div class="lang" style="position:fixed; top: 50%; right: 10px; z-index: 10">
            <a href="#" style="float:left; clear: both; display: block;"    ><img style="height:25px; margin-bottom: 5px;" src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/fb.png"></a>
            <a href="#" style="float:left;clear: both; display: block;"  ><img style="height:25px; margin-bottom: 5px;" src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/instagram.png"></a>
            <a href="#" style="float:left;clear: both; display: block;"  ><img style="height:25px; margin-bottom: 5px;" src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/tripadvisor.png"></a>
        </div>
        <?php /** FORMULARIO FLOTANTE DE RESERVAS * */ Pages_Widget_Reservation::getInstance()->setLan($this->lan)->render(); ?>


        <?php Pages_Widget_Reservation::getInstance()->render(); ?>
        <div class="pace-overlay"></div>
        <div class="menu navbar navbar-static-top header-logo-left-menu-right oxy-mega-menu navbar-sticky text-none"
             id="masthead">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggle collapsed" data-target=".main-navbar" data-toggle="collapse" type="button">
                        <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>
                    <a class="navbar-brand" style="clear:both" href="<?= Com_Helper_Url::getInstance()->urlBase ?>"> <img
                            alt="Lambda Theme - Hotel"
                            src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/logohotel1.png">
                    </a>

                </div>
                <div class="nav-container">
                    <nav class="collapse navbar-collapse main-navbar logo-navbar navbar-right">
                        <div class="menu-container">
                            <ul class="nav navbar-nav" id="menu-main">
                                <?PHP Menu_Widget_Menu::getInstance()->setLan($this->lan)->setParent(1)->render(); ?>
                            </ul>
                        </div>
                        <div class="menu-sidebar">

                            <div class="sidebar-widget widget_social">
                                <?PHP Pages_Widget_SocialIcons::getInstance()->render(); ?>
                            </div>
                        </div>
                    </nav>
                </div>

            </div>
        </div>
        <div id="content" role="main">
            <article>
                <section class="section portada" id="about">
                    <div class="background-media"
                         style="background-image: url(<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo Images_Helper_Image::getInstance()->get($this->lan, 'bannerHome')->ImgFile; ?>); background-repeat:no-repeat; background-size:cover; background-attachment:fixed; background-position: 50% 0%;"></div>
                    <div class="background-overlay grid-overlay-0" style="background-color: rgba(0, 0, 0, 0.30);"></div>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="divider-wrapper">
                                    <div class="visible-xs element-height-50"></div>
                                    <div class="visible-sm element-height-100"></div>
                                    <div class="visible-md element-height-200"></div>
                                    <div class="visible-lg element-height-200"></div>
                                </div>
                                <h1 class="text-center element-bottom-20 text-light os-animation hyper"
                                    data-os-animation="fadeIn" data-os-animation-delay="0.1s">
                                        <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'titleHome')->TxtDescription; ?>
                                </h1>
                                <h1 class="text-center element-top-20 element-bottom-20 text-light os-animation bigger regular"
                                    data-os-animation="fadeIn" data-os-animation-delay="0.2s">
                                    <em><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'subTitleHome')->TxtDescription; ?></em>
                                </h1>
                                <div class="figure os-animation" data-os-animation="fadeIn"
                                     data-os-animation-delay="0.3s"> <span class="figure-image">
                                        <img alt="decor-big-white.png"
                                             src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/decor-big-white.png">
                                    </span></div>
                                <div class="divider-wrapper">
                                    <div class="visible-xs element-height-30"></div>
                                    <div class="visible-sm element-height-30"></div>
                                    <div class="visible-md element-height-30"></div>
                                    <div class="visible-lg element-height-30"></div>
                                </div>
                                <a class="btn btn-link btn-lg text-light btn-header scroll-to-id element-top-20 element-bottom-20 os-animation"
                                   data-os-animation="fadeIn" data-os-animation-delay="0.5s"
                                   href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "page/habitaciones.html"); ?>"
                                   target="_self">
                                       <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'btnVerHabitaciones')->TxtDescription; ?>
                                </a>
                                <div class="divider-wrapper">
                                    <div class="visible-xs element-height-50"></div>
                                    <div class="visible-sm element-height-100"></div>
                                    <div class="visible-md element-height-100"></div>
                                    <div class="visible-lg element-height-100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="section" id="formulario">
                    <div class="background-media"
                         style="background-image: url(<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/bluredHome.jpg); background-repeat:no-repeat; background-size:cover; background-attachment:fixed; background-position: 50% 0%;"></div>
                    <div class="background-overlay grid-overlay-0" style="background-color: rgba(0,0,0,0.3);"></div>
                    <div class="container container-vertical-middle">
                        <div class="row vertical-middle">
                            <div class="col-md-12 text-center">
                                <div class="divider-wrapper">
                                    <div class="visible-xs element-height-40"></div>
                                    <div class="visible-sm element-height-40"></div>
                                    <div class="visible-md element-height-40"></div>
                                    <div class="visible-lg element-height-40"></div>
                                </div>
                                <form action="contact_mailer_hotel.php" class="contact-form">
                                    <div class="row vertical-middle">
                                        <div class="col-md-3 text-light">
                                            <div class="form-group  text-left">
                                                <label><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtLlegada')->TxtDescription; ?></label>
                                                <div class="date-wrapper">
                                                    <input type="text" name="datepickerin" size="40"
                                                           class="form-control datepicker"
                                                           placeholder="<?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtSeleccioneLlegada')->TxtDescription; ?>"
                                                           required></div>
                                            </div>
                                        </div>
                                        <div class="col-md-3 text-light">
                                            <div class="form-group text-left">
                                                <label><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtSalida')->TxtDescription; ?></label>
                                                <div class="date-wrapper">
                                                    <div class="date-wrapper">
                                                        <input type="text" name="datepickerout" size="40"
                                                               class="form-control datepicker"
                                                               placeholder="<?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtSeleccioneSalida')->TxtDescription; ?>"
                                                               required></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3 text-light">
                                            <div class="form-group text-left">
                                                <label><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtTipoHabitacion')->TxtDescription; ?></label>
                                                <br>
                                                <select name="type">
                                                    <?PHP Room_Widget_List::getInstance()->setLan($this->lan)->render(); ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group text-center">
                                                <label>&nbsp;</label>
                                                <br>
                                                <input class="btn btn-primary" type="submit"
                                                       value="<?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'btnReserve')->TxtDescription; ?>">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="messages"></div>
                                </form>
                                <div class="divider-wrapper">
                                    <div class="visible-xs element-height-40"></div>
                                    <div class="visible-sm element-height-40"></div>
                                    <div class="visible-md element-height-40"></div>
                                    <div class="visible-lg element-height-40"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="section">
                    <div class="background-media" data-0-top-bottom="background-position: 50% -80px"
                         data-start="background-position: 50% 0px"
                         style="background-image: url(<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo Images_Helper_Image::getInstance()->get($this->lan, 'homeHabitaciones')->ImgFile; ?>); background-repeat:no-repeat; background-size:cover; background-attachment:fixed; background-position: 50% 0%;">
                    </div>
                    <div class="background-overlay grid-overlay-0" style="background-color: rgba(86,154,167,0);"></div>
                    <div class="container-fullwidth container-vertical-middle">
                        <div class="row vertical-middle">
                            <div class="col-md-6" style="background:rgba(255, 255, 255, 0.75);">
                                <div class="row">
                                    <div class="col-md-2"></div>
                                    <div class="col-md-8 text-center">
                                        <h2 class="element-top-100 os-animation big" data-os-animation="fadeIn"
                                            data-os-animation-delay="0.1s">
                                                <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'titleHabitaciones')->TxtDescription; ?>
                                        </h2>
                                        <div class="figure os-animation" data-os-animation="fadeIn"
                                             data-os-animation-delay="0.2s"> <span class="figure-image">
                                                <img alt="decor-small-gold.png"
                                                     src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/decor-small-gold.png">
                                            </span></div>
                                        <div class="col-text-1 element-top-20 element-bottom-20 os-animation"
                                             data-os-animation="fadeIn" data-os-animation-delay="0.3s">
                                                 <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'contentHabitaciones')->TxtDescription; ?>
                                        </div>
                                        <a class="btn btn-primary btn-normal element-top-20 element-bottom-100 os-animation"
                                           data-os-animation="fadeIn" data-os-animation-delay="0.4s"
                                           href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "page/habitaciones.html"); ?>"
                                           target="_self">
                                               <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtVerMas')->TxtDescription; ?>
                                        </a></div>
                                    <div class="col-md-2"></div>
                                </div>
                            </div>
                            <div class="col-md-6 text-center"></div>
                        </div>
                    </div>
                </section>
                <section class="section">
                    <div class="background-media" data-0-top-bottom="background-position: 50% -80px"
                         data-start="background-position: 50% 0px"
                         style="background-image: url(<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo Images_Helper_Image::getInstance()->get($this->lan, 'homeRestaurante')->ImgFile; ?>); background-repeat:no-repeat; background-size:cover; background-attachment:fixed; background-position: 50% 0%;">
                    </div>
                    <div class="background-overlay grid-overlay-0" style="background-color: rgba(86,154,167,0);"></div>
                    <div class="container-fullwidth container-vertical-middle">
                        <div class="row vertical-middle">
                            <div class="col-md-6">
                            </div>
                            <div class="col-md-6" style="background:rgba(255, 255, 255, 0.75);">
                                <div class="row">
                                    <div class="col-md-2"></div>
                                    <div class="col-md-8 text-center">
                                        <h2 class="element-top-100 os-animation big" data-os-animation="fadeIn"
                                            data-os-animation-delay="0.1s">
                                                <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'titleRestaurantes')->TxtDescription; ?>
                                        </h2>
                                        <div class="figure element-top-0 element-bottom-0 os-animation"
                                             data-os-animation="fadeIn" data-os-animation-delay="0.2s"> <span
                                                class="figure-image">
                                                <img alt="decor-small-gold.png"
                                                     src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/decor-small-gold.png">
                                            </span></div>
                                        <div class="col-text-1 element-top-20 element-bottom-20 os-animation"
                                             data-os-animation="fadeIn" data-os-animation-delay="0.3s">
                                                 <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'contentRestaurantes')->TxtDescription; ?>
                                        </div>
                                        <a class="btn btn-primary element-top-20 element-bottom-100 os-animation"
                                           data-os-animation="fadeIn" data-os-animation-delay="0.4s"
                                           href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "page/restaurante.html"); ?>"
                                           target="_self">
                                               <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtVerMas')->TxtDescription; ?>
                                        </a></div>
                                    <div class="col-md-2"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="section">
                    <div class="background-media" data-0-top-bottom="background-position: 50% -80px"
                         data-start="background-position: 50% 0px"
                         style="background-image: url(<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo Images_Helper_Image::getInstance()->get($this->lan, 'homeEventos')->ImgFile; ?>); background-repeat:no-repeat; background-size:cover; background-attachment:fixed; background-position: 50% 0%;">
                    </div>
                    <div class="background-overlay grid-overlay-0" style="background-color: rgba(86,154,167,0);"></div>
                    <div class="container-fullwidth container-vertical-middle">
                        <div class="row vertical-middle">
                            <div class="col-md-6" style="background:rgba(255, 255, 255, 0.75);">
                                <div class="row">
                                    <div class="col-md-2"></div>
                                    <div class="col-md-8 text-center">
                                        <h2 class="element-top-100 os-animation big" data-os-animation="fadeIn"
                                            data-os-animation-delay="0.1s">
                                                <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'titleEventos')->TxtDescription; ?>
                                        </h2>
                                        <div class="figure element-top-0 element-bottom-0 os-animation"
                                             data-os-animation="fadeIn" data-os-animation-delay="0.2s"> <span
                                                class="figure-image">
                                                <img alt="decor-small-gold.png"
                                                     src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/decor-small-gold.png">
                                            </span></div>
                                        <div class="col-text-1 element-top-20 element-bottom-20 os-animation"
                                             data-os-animation="fadeIn" data-os-animation-delay="0.3s">
                                                 <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'contentEventos')->TxtDescription; ?>
                                        </div>
                                        <a class="btn btn-primary btn-normal element-top-20 element-bottom-100 os-animation"
                                           data-os-animation="fadeIn" data-os-animation-delay="0.4s"
                                           href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "page/salones.html"); ?>"
                                           target="_self"><?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtVerMas')->TxtDescription; ?></a>
                                    </div>
                                    <div class="col-md-2"></div>
                                </div>
                            </div>
                            <div class="col-md-6 text-center"></div>
                        </div>
                    </div>
                </section>
                <section class="section">
                    <div class="background-media" data-0-top-bottom="background-position: 50% -80px"
                         data-start="background-position: 50% 0px"
                         style="background-image: url(<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo Images_Helper_Image::getInstance()->get($this->lan, 'homeOpiniones')->ImgFile; ?>); background-repeat:no-repeat; background-size:cover; background-attachment:fixed; background-position: 50% 0%;">
                    </div>
                    <div class="background-overlay grid-overlay-0" style="background-color: rgba(0, 0, 0, 0.62);"></div>
                    <div class="container container-vertical-middle">
                        <div class="row vertical-middle">

                            <div class="col-md-5 text-center">
                                <?PHP Promos_Widget_Important::getInstance()->setLan($this->lan)->setLimit(1)->render(); ?>
                            </div>
                            <div class="col-md-2 text-center"></div>
                            <div class="col-md-5 text-center">
                                <h2 class="text-default element-top-100 element-bottom-0 text-light os-animation big default"
                                    data-os-animation="fadeIn" data-os-animation-delay="0.1s">
                                        <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'titleReviews')->TxtDescription; ?>
                                </h2>
                                <div class="figure os-animation" data-os-animation="fadeIn"
                                     data-os-animation-delay="0.2s"> <span class="figure-image">
                                        <img alt="decor-small-white.png"
                                             src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/decor-small-white.png">
                                    </span></div>
                                <div
                                    class="element-top-20 element-bottom-100 text-center text-light os-animation flexslider feature-slider"
                                    data-flex-animation="slide" data-flex-controls="show" data-flex-controls-position="outside"
                                    data-flex-controlsalign="center"
                                    data-flex-directions="hide" data-flex-slideshow="true" data-flex-speed="7000"
                                    data-os-animation="fadeIn" data-os-animation-delay="0.3s" id="flexslider-116">
                                    <ul class="slides">
                                        <?PHP Reviews_Widget_Reviews::getInstance()->setLimit(5)->render(); ?>
                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                </section>
                <!--                <section class="section">
                            <div class="background-overlay grid-overlay-0" style="background-color: rgba(86,154,167,0);"></div>
                            <div class="container-fullwidth container-vertical-middle">
                                <div class="row vertical-middle">
                                    <div class="col-md-6">
                                        <div class="google-map" data-os-animation="none" data-os-animation-delay="0s" id="map" style="height:500px"></div>
                                    </div>
                                    <div class="col-md-6 text-center" style="background:rgba(255, 255, 255, 0.95);">
                                        <div class="row">
                                            <div class="col-md-2"></div>
                                            <div class="col-md-8 text-center">
                                                <h2 class="element-top-100 os-animation big" data-os-animation="fadeIn" data-os-animation-delay="0.1s">
                <?PHP //echo Texts_Helper_Text::getInstance()->get($this->lan, 'titleNuestraUbicacion')->TxtDescription; ?>
                                                </h2>
                                                <div class="figure os-animation" data-os-animation="fadeIn" data-os-animation-delay="0.2s"> <span class="figure-image">
                                                        <img alt="decor-small-gold.png" src="<?PHP // echo Com_Helper_Url::getInstance()->getImage();  ?>/Public/hotel/decor-small-gold.png">
                                                    </span> </div>
                                                <div class="col-text-1 element-top-20 element-bottom-100 os-animation" data-os-animation="fadeIn" data-os-animation-delay="0.3s">
                                                    <p><?PHP //echo Texts_Helper_Text::getInstance()->get($this->lan, 'contentNuestraUbicacion')->TxtDescription;  ?></p>
                                                </div>
                                            </div>
                                            <div class="col-md-2"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>-->
            </article>
            <footer id="footer">
                <?PHP Pages_Widget_Contacto::getInstance()->setLan($this->lan)->render(); ?>
            </footer>
            <script
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&amp;sensor=false"></script>
        </div>

        <script type="text/javascript">
            var oxyThemeData = {
                navbarHeight: 90,
                navbarScrolled: 80,
                navbarScrolledPoint: 100,
                menuClose: 'off',
                scrollFinishedMessage: 'No more items to load.',
                hoverMenu: {
                    hoverActive: false,
                    hoverDelay: 200,
                    hoverFadeDelay: 200
                },
                siteLoader: 'on'
            };
        </script>


        <?php
        Com_Helper_Script::getInstance()
                ->addFile("Public/theme.js")
                ->addFile("Public/contact.js")
                ->addFile("Public/map.js");
        echo Com_Helper_Script::getInstance();
        ?>

        <script>
            window.map = {
                map_type: 'ROADMAP',
                map_zoom: 17,
                map_style: 'blackwhite',
                map_scrollable: 'on',
                marker: 'show',
                label: ['Hotel Cortez'],
                address: '',
                latlng: ['-17.771060, -63.184124'],
                center_latlng: '',
                markerURL: '<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/marker.png',
                auto_center: true
            };
        </script>
        <!-- Smartsupp Live Chat script -->
        <script type="text/javascript">
            var _smartsupp = _smartsupp || {};
            _smartsupp.key = '7297473a650eaeeecd1c8851f4eee1f1def96bb7';
            window.smartsupp || (function (d) {
                var s, c, o = smartsupp = function () {
                    o._.push(arguments)
                };
                o._ = [];
                s = d.getElementsByTagName('script')[0];
                c = d.createElement('script');
                c.type = 'text/javascript';
                c.charset = 'utf-8';
                c.async = true;
                c.src = '//www.smartsuppchat.com/loader.js?';
                s.parentNode.insertBefore(c, s);
            })(document);
        </script>
        <script>
            $(window).scroll(function () {
                $('#aux').css('transform', 'translate(0,100%)');
            });
        </script>


    </body>

</html>