<!doctype html>
<html class="no-js" lang="">

    <head>
        <?php $actual_link = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
        Seo_Widget_Seo::getInstance()->setLan($this->lan)->setPage("Servicios")->setUrl($actual_link)->render(); ?>

        <link rel='stylesheet' id='open-sans-css'
              href='//fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=4.1'
              type='text/css' media='all'/>
        <link
            href="//fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,700,800%7CPlayfair+Display:400,400italic,700,900&amp;subset=greek,latin,latin"
            rel="stylesheet" type="text/css">


        <meta name="msapplication-TileColor" content="#d9534f">
        <meta name="msapplication-TileImage"
              content="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/ms-icon-144x144.png">
        <meta name="msapplication-config"
              content="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public//favicons/browserconfig.xml">
        <meta name="theme-color" content="#ffffff">
        <link rel="apple-touch-icon" sizes="57x57"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-180x180.png">
        <link rel="icon" type="image/png"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-32x32.png"
              sizes="32x32">
        <link rel="icon" type="image/png"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/android-192x192.png"
              sizes="192x192">
        <link rel="icon" type="image/png"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-96x96.png"
              sizes="96x96">
        <link rel="icon" type="image/png"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-16x16.png"
              sizes="16x16">
        <link rel="manifest" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/manifest.json">
        <link rel="shortcut icon"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon.ico"
              type="image/x-icon"/>

        <?PHP
        Com_Helper_Style::getInstance()
                ->addFile("Public/extras.min.css")
                ->addFile("Public/bootstrap.css")
                ->addFile("Public/font-awesome.min.css")
                ->addFile("Public/fonts.css")
                ->addFile("Public/theme.css")
                ->addFile("Public/hotel.css");
        echo Com_Helper_Style::getInstance();
        ?>
    </head>

    <body class="transparent-header pace-on pace-dot">
        <?php /** FORMULARIO FLOTANTE DE RESERVAS * */ Pages_Widget_Reservation::getInstance()->setLan($this->lan)->render(); ?>
        <div class="pace-overlay"></div>
        <div class="menu navbar navbar-static-top header-logo-left-menu-right oxy-mega-menu navbar-sticky text-none"
             id="masthead">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggle collapsed" data-target=".main-navbar" data-toggle="collapse" type="button">
                        <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>
                    <a class="navbar-brand" href="<?= Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode,''); ?>"> <img alt="Lambda Theme - Hotel"
                                                                                                      src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/hotel/logohotel1.png">
                    </a>
                </div>
                <div class="nav-container">
                    <nav class="collapse navbar-collapse main-navbar logo-navbar navbar-right">
                        <div class="menu-container">
                            <ul class="nav navbar-nav" id="menu-main">
                                <?PHP Menu_Widget_Menu::getInstance()->setLan($this->lan)->setParent(1)->render(); ?>
                            </ul>
                        </div>
                        <div class="menu-sidebar">
                            <div class="sidebar-widget widget_social">
                                <?PHP //Pages_Widget_SocialIcons::getInstance()->render(); ?>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <div id="content" role="main">
            <article>
                <section class="section portada">
                    <div class="background-media"
                         style="background-image: url(<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo Images_Helper_Image::getInstance()->get($this->lan, 'bannerServicios')->ImgFile; ?>); background-repeat:no-repeat; background-size:cover; background-attachment:fixed; background-position: 50% 50%;"></div>
                    <div class="background-overlay grid-overlay-0" style="background-color: rgba(0,0,0,0.4);"></div>
                    <div class="container portada-center">
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="divider-wrapper">
                                    <div class="visible-xs element-height-100"></div>
                                    <div class="visible-sm element-height-100"></div>
                                    <div class="visible-md element-height-190"></div>
                                    <div class="visible-lg element-height-190"></div>
                                </div>
                                <h1 class="text-center element-bottom-20 text-light os-animation hyper"
                                    data-os-animation="fadeIn" data-os-animation-delay="0.1s">
                                        <?PHP echo Texts_Helper_Text::getInstance()->get($this->lan, 'titleServicios')->TxtDescription; ?>
                                </h1>

                                <div class="figure os-animation" data-os-animation="fadeIn"
                                     data-os-animation-delay="0.3s"> <span class="figure-image">
                                    <!-- <img alt="decor-big-white.png" src="<?PHP //echo Com_Helper_Url::getInstance()->getImage();  ?>/Public/hotel/decor-big-white.png"> -->
                                    </span></div>
                                <div class="divider-wrapper">
                                    <div class="visible-xs element-height-100"></div>
                                    <div class="visible-sm element-height-100"></div>
                                    <div class="visible-md element-height-100"></div>
                                    <div class="visible-lg element-height-100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <?PHP Service